### ISSUE TITLE
spglib ~=2.0 breaks the package

### ISSUE THREAD

**Issue by zhubonan** [ajjackson/mctools#3]
spglib ~= 2.0 no longer supports `ase.Atoms` for input in its python APIs.

**Comment by ajjackson** [comment]
Indeed! I have been starting to update/modernise this collection a bit. I'd like to

- reorganise the repo so it is easier to keep track of which scripts go with what external tools
- add some unit tests and CI, which will make such compatibility problems easier to identify
- overhaul the scripts to use Typer, for prettier UI
- update requirements to fairly recent package versions, and clear deprecation warnings

The spglib fix is a quick and simple job, but it would also be a good test that the CI is working properly so I'd like to defer it until a unit test is in place!
